---
- name: Instalaci贸n y configuraci贸n de HAProxy
  hosts: loadbalancers
  remote_user: root
  tasks:
    - name: Instalaci贸n de HAProxy
      apt:
        name: haproxy
        state: latest
    - name: Enviar fichero de configuraci贸n
      copy:
        src: /root/practicaclase/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
    - name: Comprobar que el servicio esta levantado
      service:
        name: haproxy
        state: started
...
